### PR TITLE
hide TLS support behind feature

### LINKED ISSUE #6: tls support should be behind a feature
same as #5 , 

when we don't need it, it adds many dependencies we don't need

### PR DESCRIPTION
**Pull request by syphar**
resolves #6

### CODE REVIEW

**Comment by MidasLamb** [comment]
Thanks for the effort! But I'm not sure that having the `websocket` feature also means you need the `tls` one. But to cleanly support this, I think I'll need to do a bit of refactoring for the security scheme.
I have to think about it a bit more, but it might be that I'll fix #6 myself with all the refactoring I have in mind.

**Comment by syphar** [comment]
valid points, somehow I remembered that websockets were always TLS, but I might be wrong. 

If you don't need this, just close it.  :)

**Comment by MidasLamb** [comment]
I'm not sure yet what the best approach forward is, I've never used websockets myself in any real project, so I'm not super familiar with them.
But I think that support for websockets over TLS is handled by `tokio-tungstenite` internally, so for tls support in websockets in `axum-strangler`, we still wouldn't need `hyper-tls`.
But I need to let it swirl around in my head a bit before I decide on any direction to take.

**Comment by MidasLamb** [comment]
I've done some refactoring in order to more cleanly support this and the websockets: #12 
Thanks for the effort and your help making this project better!

**Pull request closed without merging**
